// User dictionaries are kept separately from the bundled JMdict data.
let pendingImport=null,customSession=null;
function customKey(w){return w.w.normalize('NFKC').trim()+'\u0000'+w.r.normalize('NFKC').trim()}
function parseCSV(source){
 const text=source.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false,closed=false,line=1,start=1;
 const push=()=>{row.push(cell);cell='';closed=false};
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++}else{quoted=false;closed=true}}else{cell+=c;if(c==='\n')line++}continue}
 if(c==='"'){if(cell||closed)throw Error(`第 ${line} 行：引号位置不正确`);quoted=true}
 else if(c===','){push()}
 else if(c==='\r'||c==='\n'){if(c==='\r'&&text[i+1]==='\n')i++;push();if(row.some(v=>v.trim()))rows.push({cells:row,line:start});row=[];line++;start=line}
 else{if(closed)throw Error(`第 ${line} 行：结束引号后只能是逗号或换行`);cell+=c}
 }
 if(quoted)throw Error(`第 ${start} 行：双引号未闭合`);push();if(row.some(v=>v.trim()))rows.push({cells:row,line:start});return rows;
}
const csvFields=['单词','假名','释义','词性','例句','例句翻译'];
function validateCSV(text){const rows=parseCSV(text);if(rows.length<2)throw Error('请包含表头和至少一行单词。');let header=rows.shift().cells.map(s=>s.trim());if(new Set(header).size!==header.length)throw Error('表头有重复列。');if(header.some(h=>!csvFields.includes(h)))throw Error('表头仅支持：'+csvFields.join('、'));for(const h of csvFields.slice(0,3))if(!header.includes(h))throw Error('缺少必填列：'+h);if(rows.length>5000)throw Error('每次最多导入 5,000 行。');return rows.map(row=>{if(row.cells.length!==header.length)throw Error(`第 ${row.line} 行：列数与表头不一致`);let obj=Object.fromEntries(header.map((h,i)=>[h,row.cells[i].trim()]));for(const h of csvFields.slice(0,3))if(!obj[h])throw Error(`第 ${row.line} 行：${h}不能为空`);if(row.cells.some(v=>v.length>4000))throw Error(`第 ${row.line} 行：单个字段最多 4,000 字符`);return {w:obj['单词'],r:obj['假名'],zh:obj['释义'],pos:obj['词性']||'自定义',ex:obj['例句']||'',cn:obj['例句翻译']||'',en:'',aliases:obj['单词']+' '+obj['假名'],custom:true}})}
function importWords(words){const keys=new Set(state.custom.map(customKey)),added=[];for(const w of words){const key=customKey(w);if(keys.has(key))continue;keys.add(key);added.push({...w,id:'user-'+crypto.randomUUID()})}if(!added.length)return {added:0,skipped:words.length};if(state.custom.length+added.length>10000)throw Error('自定义词库最多保存 10,000 词。');const next={...state,custom:[...state.custom,...added]};try{localStorage.setItem('komorebi-v1',JSON.stringify(next))}catch{throw Error('本地存储空间不足或保存被禁用，本次没有写入。请减少导入数量。')}state=next;for(const w of added){DATA.push(w);byId.set(w.id,w)}return {added:added.length,skipped:words.length-added.length}}
function downloadText(name,text,type){if(window.chrome?.webview){window.chrome.webview.postMessage({kind:"saveFile",name,text});return;}if(window.webkit?.messageHandlers?.saveFile){window.webkit.messageHandlers.saveFile.postMessage({name,text});return;}const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function renderImport(){pendingImport=null;$('#view').innerHTML=`<div class="panel settings import-panel"><div class="import-heading"><div><h3>自己的词，也有一席之地。</h3><p class="muted">已保存 ${state.custom.length} 个自定义词 · 仅保存在这台设备</p></div><button id="custom-study" class="primary">学习我的词库 →</button></div><h3>CSV 批量导入</h3><p>使用 Excel 或其他表格工具编辑，然后另存为 <b>CSV UTF-8（逗号分隔）</b>。首行是列名，顺序可以调整。</p><div class="table-wrap"><table><thead><tr>${csvFields.map((h,i)=>`<th>${h}${i<3?' <small>必填</small>':' <small>选填</small>'}</th>`).join('')}</tr></thead><tbody><tr><td>桜</td><td>さくら</td><td>樱花</td><td>名词</td><td>桜が咲いています。</td><td>樱花正在盛开。</td></tr></tbody></table></div><p class="muted">每次最多 5,000 行、2 MB，累计最多 10,000 词。含逗号、换行的单元格需用双引号包裹（表格软件会自动处理）。<br>按“单词 + 假名”跳过已有自定义词和文件内重复行；内置词典保持不变。有格式错误时整批不写入。</p><div class="import-buttons"><button id="template" class="outline">下载 CSV 模板</button><label class="upload-label">选择 CSV 文件<input id="csv-file" type="file" accept=".csv,text/csv"></label><button id="custom-export" class="outline">导出我的词库</button></div><div id="import-result" role="status" aria-live="polite"></div><hr><h3>手动添加一个单词</h3><form id="manual-form"><div class="manual-grid">${csvFields.map((h,i)=>`<label>${h}${i<3?' *':''}<input name="f${i}" ${i<3?'required':''} maxlength="4000" placeholder="${['例：桜','例：さくら','例：樱花','例：名词','例：桜が咲いています。','例：樱花正在盛开。'][i]}"></label>`).join('')}</div><button class="primary" type="submit">添加并保存</button><span id="manual-result" role="status" style="margin-left:15px"></span></form></div>`;
 $('#template').onclick=()=>downloadText('木漏れ日-词库模板.csv','\uFEFF'+csvFields.join(',')+'\r\n桜,さくら,樱花,名词,桜が咲いています。,樱花正在盛开。\r\n','text/csv;charset=utf-8');
 $('#custom-export').onclick=()=>{if(!state.custom.length){toast('还没有自定义单词。');return}const cell=v=>'"'+String(v||'').replace(/"/g,'""')+'"';downloadText('木漏れ日-我的词库.csv','\uFEFF'+csvFields.join(',')+'\r\n'+state.custom.map(w=>[w.w,w.r,w.zh,w.pos,w.ex,w.cn].map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8')};
 $('#custom-study').onclick=()=>{if(!state.custom.length){toast('先添加或导入一些单词吧。');return}customSession=state.custom.map(w=>w.id);tab='study';detail=null;index=0;revealed=!state.hide;render()};
 $('#csv-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;pendingImport=null;const result=$('#import-result');result.textContent='正在检查文件…';try{if(file.size>2*1024*1024)throw Error('文件超过 2 MB，请拆分后再导入。');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());const words=validateCSV(text);if(!result.isConnected)return;pendingImport=words;const known=new Set(state.custom.map(customKey));let fresh=0;for(const w of words){const key=customKey(w);if(!known.has(key)){fresh++;known.add(key)}}result.innerHTML=`<div class="import-preview"><b>${esc(file.name)}</b><p>格式检查通过 · ${fresh} 个新词 · ${words.length-fresh} 行重复将跳过</p>${words.slice(0,3).map(w=>`<p>${esc(w.w)} · ${esc(w.r)} · ${esc(w.zh)}</p>`).join('')}<button id="confirm-import" class="primary" ${fresh?'':'disabled'}>导入并保存 ${fresh} 个单词</button></div>`;$('#confirm-import').onclick=()=>{try{const r=importWords(pendingImport);renderImport();$('#import-result').textContent=`已保存 ${r.added} 个新词，跳过 ${r.skipped} 行重复。可在词汇手册选择“我的词库”。`}catch(err){result.textContent=err.message}}}catch(err){if(result.isConnected)result.textContent=err instanceof TypeError?'文件不是有效 UTF-8，请另存为 CSV UTF-8 后重试。':err.message}};
 $('#manual-form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),values=csvFields.map((_,i)=>String(f.get('f'+i)||'').trim());try{const words=validateCSV(csvFields.join(',')+'\n'+values.map(v=>'"'+v.replace(/"/g,'""')+'"').join(','));const r=importWords(words);if(!r.added){$('#manual-result').textContent='此单词和假名已存在，未重复添加。';return}renderImport();$('#manual-result').textContent='已保存，可在我的词库中学习。'}catch(err){$('#manual-result').textContent=err.message}};
}
