import {Window} from 'happy-dom';
import fs from 'node:fs';import assert from 'node:assert/strict';import vm from 'node:vm';
const window=new Window({url:'http://localhost:8765/'});window.Worker=class{postMessage(){}};window.URL.createObjectURL=()=> 'blob:test';window.URL.revokeObjectURL=()=>{};
let html=fs.readFileSync('web/index.html','utf8');window.document.write(html.replace(/<script>[\s\S]*?<\/script>/g,''));
window.eval(html.split('<script>').at(-1).split('</script>')[0]+`\nwindow.TEST={getState:()=>state,difficulty,navigate,render,renderListResults,validateCSV,importWords,rubyWord,norm,getWords:()=>DATA,getLevel:()=>listLevel};`);
const T=window.TEST,d=window.document;
T.navigate('dictionary');let input=d.querySelector('#search');
input.dispatchEvent(new window.CompositionEvent('compositionstart',{bubbles:true}));input.value='インフルエンザ';input.dispatchEvent(new window.InputEvent('input',{bubbles:true,isComposing:true}));input.dispatchEvent(new window.CompositionEvent('compositionend',{bubbles:true,data:'インフルエンザ'}));
assert.equal(d.querySelector('#search'),input,'IME input node must stay attached');assert.ok(d.querySelector('#list-results').textContent.includes('インフルエンザ'));d.querySelector('#search-form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));assert.ok(d.querySelectorAll('.row').length>0);
for(const q of ['ｲﾝﾌﾙｴﾝｻﾞ','いんふるえんざ',' インフルエンザ ']){input.value=q;input.dispatchEvent(new window.InputEvent('input',{bubbles:true}));assert.ok(d.querySelectorAll('.row').length>0,q)}
input.value='';input.dispatchEvent(new window.InputEvent('input',{bubbles:true}));d.querySelector('#list-level').value='N5';d.querySelector('#list-level').dispatchEvent(new window.Event('change'));assert.ok([...d.querySelectorAll('.row .level-badge')].every(e=>e.textContent==='N5'));
T.navigate('study');d.querySelector('#study-source').value='all';d.querySelector('#study-source').dispatchEvent(new window.Event('change'));d.querySelector('#study-level').value='N1';d.querySelector('#study-level').dispatchEvent(new window.Event('change'));assert.equal(d.querySelector('.card-top .level-badge').textContent,'N1');
let custom=T.validateCSV('单词,假名,释义,等级\n試験用,しけんよう,测试用词,N4');assert.equal(custom[0].level,'N4');assert.throws(()=>T.validateCSV('单词,假名,释义,等级\n桜,さくら,樱花,N6'));T.importWords(custom);T.navigate('import');d.querySelector('#custom-study').click();assert.ok(d.querySelector('.card-top .level-badge').textContent.includes('N4'));assert.ok(d.querySelector('.word ruby rt'));
assert.equal(T.rubyWord('<img src=x>','あ'), '&lt;img src=x&gt;');assert.equal(T.norm('ｲﾝﾌﾙｴﾝｻﾞ'),'いんふるえんざ');
const counts={};for(const w of T.getWords()){let l=T.difficulty(w);counts[l]=(counts[l]||0)+1}console.log('PASS: IME commit, Enter, stable input identity, hiragana/katakana/fullwidth normalization, list/study filters, custom CSV levels, ruby escaping');console.log(counts);
// Test real offline tokenizer in an isolated worker-like context.
let messages=[];const workerContext=vm.createContext({Uint8Array,Uint32Array,Int32Array,Int16Array,ArrayBuffer,TextDecoder,TextEncoder,atob,console,self:{postMessage:m=>messages.push(m)}});vm.runInContext(fs.readFileSync('build/worker.bundle.js','utf8'),workerContext);const dicts={};for(const name of fs.readdirSync('node_modules/kuromoji/dict'))if(name.endsWith('.gz'))dicts[name]=fs.readFileSync('node_modules/kuromoji/dict/'+name).toString('base64');workerContext.self.onmessage({data:{type:'init',dicts}});assert.equal(messages[0].type,'ready');workerContext.self.onmessage({data:{type:'annotate',id:1,text:'毎朝、学校で日本語を勉強します。'}});const result=messages[1];assert.equal(result.type,'result');assert.ok(result.tokens.some(t=>t.text==='学校'&&t.reading==='ガッコウ'));assert.ok(result.tokens.some(t=>t.text==='勉強'&&t.reading==='ベンキョウ'));console.log('PASS: embedded IPADIC loads, Japanese sentence token readings',result.tokens);
window.happyDOM.abort();
